# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Shadow
enable_shadow = true

# Set this to true if you want to use old LWJGL2 methods.
enable_lwjglx = true

# Mod Information
mod_version = 26.1.0
root_package = me.shedaniel.cloth
mod_id = cloth_config
mod_name = Cloth Config v26.1 API

# Mod Metadata
mod_description = An API for config screens.
mod_url = https://minecraft.curseforge.com/projects/cloth-config
mod_update_json =
mod_authors = shedaniel
mod_credits =
mod_logo_path =

# Catalogue Extra Metadata
mod_license = GNU LGPLv3
mod_issue_tracker_url = https://github.com/shedaniel/ClothConfig/issues
mod_icon_path = icon.png
mod_icon_item =
mod_background_path =

# Run Configurations
minecraft_username = Dev
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing (Provide secret: MAVEN_USER, MAVEN_PASS)
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Coremods
is_coremod = false
coremod_includes_mod = false
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
